apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: applications
  namespace: argocd

spec:
  description: Applications

  sourceRepos:
    - https://github.com/rs235/gitops.git

  destinations:
    - namespace: apps-*
      server: https://kubernetes.default.svc

  clusterResourceWhitelist: []

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

syncPolicy:
  automated:
    prune: true
    selfHeal: true

  syncOptions:
    - CreateNamespace=true
