apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: applications
  namespace: argocd

spec:
  description: Applications

  sourceRepos:
    - https://github.com/rs235/gitops

  destinations:
    - namespace: apps-*
      server: https://kubernetes.default.svc

  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: ""
      kind: Service
