apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: argocd
  namespace: argocd

spec:
  description: Argo CD management

  sourceRepos:
    - https://github.com/argoproj/argo-cd.git

  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
