kind: Application

metadata:
  name: platform

spec:
  source:
    path: platform/
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: monitoring
  namespace: argocd

spec:
  project: platform

  source:
    repoURL: https://github.com/rs235/gitops
    path: platform/monitoring

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
