apiVersion: argoproj.io/v1alpha1 # Argo CDA API version for Application object.
kind: Application # K8s object type. In this case ArgoCD Application.
metadata: # Description of the ArgoCD Application object.
  name: nginx # Name of the ArgoCD application object.
  namespace: argocd # K8s namespace for ArgoCD application object.

spec: # ArgoCD Application specification.
  project: apps # ArgoCD project name for this app.

  source: # Source of configuration.
    repoURL: https://github.com/rs235/gitops.git # Repo url.
    targetRevision: main # Repo branch.
    path: apps/nginx # Path in the repo containing app manifests.

  destination: # Destination cluster.
    server: https://kubernetes.default.svc # Destination cluster API server address.
    namespace: apps # K8s namespace for the app deployment.

  syncPolicy: # ArgoCD sync policy definition.
    automated: # Sync policy type.
      prune: true # Remove resources managed by this Application automatically if they are removed from the repo.
      selfHeal: true # Manual changes to running app are overwritten with what's in the repo.
    syncOptions: # Additional sync policy options.
      - CreateNamespace=true # Creates K8s namespace defined in this manifest if it doesn't exist.
