apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nginx
  - website

namespace: apps

replicas:
  - name: nginx
    count: 1
  - name: website
    count: 3

containers:
  - name: nginx
    image: nginx:1.30
  - name: website
    image: nginx:1.31
