apiVersion: apps/v1
kind: Deployment

metadata:
  name: website

spec:
  replicas: 1

  selector:
    matchLabels:
      app.kubernetes.io/name: website

  template:
    metadata:
      labels:
        app.kubernetes.io/name: website

    spec:
      containers:
        - name: nginx
          image: nginx:1.30
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
